### ISSUE TITLE
Error creating floating point numeral

### ISSUE THREAD

**Issue by martin-neuhaeusser** [CVC4/CVC4#2013]
Trying to test CVC4's new floating point support, we fail in creating a simple numeral:
We have two small C++ test programs that both fail:

1. Creating a 32 bit floating point number via a rational:
```c++
#include <cvc4/cvc4.h>
#include <iostream>

using namespace std;
using namespace CVC4;

void test () {
  // 32 bit IEEE754
  cout << "creating standard 32 bit floating point size" << endl;
  FloatingPointSize sz = FloatingPointSize(8, 23);

  // standard rounding mode
  cout << "creating rounding mode instance (nearest even)" << endl;
  RoundingMode rm = RoundingMode::roundNearestTiesToEven;

  // 1/2
  cout << "constructing rational 1/2" << endl;
  Rational two = Rational(1, 2);

  // floating point from rational
  cout << "constructing floating point from rational " << two << endl;
  FloatingPoint fp = FloatingPoint(sz, rm, two);

  cout << "resulting floating point number is " << fp << endl;
}

int main (int argc, char* argv[]) {
  test ();
  cout << "test succeeded" << endl;
}
```

2. Creating a 32 bit floating point number (8 bit exponent, 23 bit significand) from a bit vector:
```c++
#include <cvc4/cvc4.h>
#include <iostream>

using namespace std;
using namespace CVC4;

void test() {
  cout << "creating bit vector representing 1/2 as 32 bit IEEE754" << endl;
  BitVector bv = BitVector("00111111000000000000000000000000");
  cout << "bit vector is " << bv << " with length " << bv.getSize() << endl;

  cout << "creating floating point from bit vector..." << endl;
  FloatingPoint fp = FloatingPoint(8, 23, bv);
  cout << "floating point number is " << fp << endl;
}

int main (int argc, char* argv[]) {
  test();
  cout << "test succeeded" << endl;
}
```
Both tests abort with a CVC4::IllegalArgumentException.
Do we need to initialize anything before constructing float numerals?
Are the parameters that we use correct?

The tests were built using `c++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516` on a 64 bit Debian system.
CVC4 was built using
`configure --with-cryptominisat --with-abc --with-abc-dir=/home/marneu/solver/cvc4/abc/alanmi-abc-53f39c11b58d --with-symfpu --prefix=/home/marneu/local/ CVC4_BSD_LICENSED_CODE_ONLY=0`

The alleged error was reproducible with commits #b25c979 and #376b087.

**Comment by martin-cs** [comment]
On Fri, 2018-06-01 at 02:01 -0700, Martin R. Neuhäußer wrote:
> Thank you very much for the clarification on the hidden bit. 
> I fixed that issue in the above examples and uploaded them for your
> convenience [here.](https://github.com/martin-neuhaeusser/bug-reports
> /tree/master/cvc4-symfpu)

Brilliant; thank you.


> However, including the hidden bit does not resolve the "bad argument"
> exception that I receive.

Annoying; I'll have a look at this ASAP.


>  Is CVC4 expected to support non-standard combinations of exponent
> and significand widths, as well?

Yes in principle.  In practice ... we put our testing effort elsewhere
due to a shortage of benchmarks / clear use-cases for them.  I would
not be surprised if they break or possibly give suspect answers.  It
would be great to fix them, but, until someone can give me a useful
application and agrees to help with the (production / testing of)
benchmarks then ... it may remain a lower priority.

>  If so, at least the test case that uses a rational to construct a
> floating point numeral
> should succeed even with an unusual (and unintended) significand
> width of 23 bits, right?

It should but you would have to pass in a 31 bit bit-vector.

Cheers,
 - Martin

**Comment by martin-cs** [comment]
I've been looking into this and can reproduce it.  It seems to be some kind of problem with object lifetime during creation of the floating-point object.  Definitely a bug and definitely my fault but not yet clear how to fix it.

**Comment by martin-cs** [comment]
I'm working on the bit-vector version of the bug and have got this far:

1. I can reproduce the bug when building with g++ or clang++ so I am confident this is an "intended semantics" issue.

2. The FloatingPoint object is correctly constructed at the end of the constructor and appears to have the right value in memory (if GDB is to be believed) when *this is displayed.

3. However after the ret instruction the values in the FloatingPoint object are change but are not those that were correct in the constructor, leading to an incorrectly structured object and a crash when outputting it.

My current best guess is that this is a quirk of C++'s semantics and that it is regarding the constructed object as a temporary and over-writing it during the ret.

**Comment by martin-cs** [comment]
Right; after a bit more puzzling I've worked out what is going on here.

1. util/floatingpoint.h has a pre-processor switch that swaps whether a FloatingPointLiteral is a place-holder "not implemented" class or a SymFPU literal.  This allows you to compile CVC4 without SymFPU, although nothing floating-point related will work.

https://github.com/CVC4/CVC4/blob/master/src/util/floatingpoint.h#L290

(For extra fun, note that this is the first member in FloatingPoint ... this is significant
https://github.com/CVC4/CVC4/blob/master/src/util/floatingpoint.h#L316 )

2. When the library is built and installed, because you used --with-symfpu CVC4_USE_SYMFPU is used and so FloatingPoint contains a SymFPU literal and its size is 0x40.

3. When the application is built, CVC4_USE_SYMFPU is *not* defined, so FloatingPoint contains the place-holder class and its size is 12.

4. When the application code runs, it creates a space of 12 on the stack for the FloatingPoint object and calls the constructor.

5. The constructor is compiled with the understanding that its size is 0x40 and initialises accordingly; stamping all over the stack in the process.  Critically the FloatingPointSize field is in a different location in the constructor and the application, so everything /looks/ fine until the ret instruction.

6. ret switches control back, the FloatingPoint object has been changed but the size is wrong.  The next time it is used, it may crash as the size is out OR ... it might just continue until the next important thing on the stack that got over-written.  Hence you see an array of interesting crashes depending on the usual compilation level of detail.

How to fix this.  Well, clearly, the application code that uses the library and the library have to be compiled with the same flags.  Just blindly adding #define CVC4_USE_SYMFPU before the first include will create a problem as the SymFPU headers are not currently installed as part of ```make install```.  So I think I am going to have to call for backup:

@barrettcw @ajreynol @aniemetz @mpreiner @4tXJ7f : how do we normally make sure that the CVC4_USE_* flags are consistent and that headers from third-party libraries are included?

**Comment by martin-neuhaeusser** [comment]
Thank you for looking into the issue!
We are happy to test CVC4's IEEE754 support and provide feedback, 
once we can build our verifier with the CVC4 static library.

**Comment by 4tXJ7f** [comment]
@martin-neuhaeusser @martin-cs I just submitted #2077, which should fix the issue. With this fix, I was able to compile and run the examples successfully when configuring with --with-symfpu and got an error about unimplemented floating-point operators when not configuring it with --with-symfpu, so it seems to work. Note that I had to add the symfpu-CVC4 folder in the CVC4 directory to the include paths.

**Comment by 4tXJ7f** [comment]
@martin-neuhaeusser The PR has been merged. It would be great if you could take a look if you get the chance.

**Comment by martin-neuhaeusser** [comment]
I just ran a quick check and tried to compile our OCaml bindings. Compilation now fails when searching for the SymFPU headers. They are still missing in the set of header files that CVC4's make install deploys:

```
In file included from /home/marneu/local/include/cvc4/expr/expr.h:63:0,
                 from /home/marneu/local/include/cvc4/expr/datatype.h:37,
                 from /home/marneu/local/include/cvc4/cvc4.h:23,
                 from cvc4_stubs.c:10:
/home/marneu/local/include/cvc4/util/floatingpoint.h:29:39: fatal error: symfpu/core/unpackedFloat.h: No such file or directory
 #include <symfpu/core/unpackedFloat.h>
                                       ^
```

CVC4 was configured from scratch with
```configure --prefix=/home/marneu/local --with-abc --with-abc-dir=/home/marneu/solver/cvc4/abc/alanmi-abc-53f39c11b58d --with-cryptominisat --with-symfpu CVC4_BSD_LICENSED_CODE_ONLY=0 --with-gmp --disable-debug-symbols --enable-proof```
and installed with make install.

The CVC4 headers are correctly copied into my local include directory, but the symfpu subtree
is missing:
```
marneu@idefix:~/local/include/cvc4$ ls -la
total 72
drwxr-xr-x 15 marneu marneu 4096 Jun 21 12:24 .
drwxr-xr-x  7 marneu marneu 4096 Apr 20 08:08 ..
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 base
drwxr-xr-x  3 marneu marneu 4096 Jan 17  2017 bindings
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 compat
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 context
-rw-r--r--  1 marneu marneu 1184 Jun 21 12:24 cvc4.h
-rw-r--r--  1 marneu marneu  933 Jun 21 12:24 cvc4parser_public.h
-rw-r--r--  1 marneu marneu 2696 Jun 21 12:24 cvc4_public.h
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 expr
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 options
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 parser
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 printer
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 proof
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 smt
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 smt_util
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 theory
drwxr-xr-x  2 marneu marneu 4096 Jun 21 12:24 util
marneu@idefix:~/local/include/cvc4$ find . -name "unpackedFloat.h" 
marneu@idefix:~/local/include/cvc4$ 
```

**Comment by 4tXJ7f** [comment]
Sorry, I didn't explain well. When you compile your files, you have to add the symfpu-CVC4 directory in your include paths (i.e. I had to do `g++ -I<path to symfpu-CV4> ...`). This is because we are considering symfpu to be an external dependency, so we do not install it with CVC4. The current solution is not the most user-friendly way but we are working on making it better.

**Comment by 4tXJ7f** [comment]
I am closing this issue for now since it should be resolved.

@martin-neuhaeusser Please reopen it or open an new issue if you run into other issues.
