### ISSUE TITLE
Unreachable code in TheoryStringsRewriter::testConstStringInRegExp()

### ISSUE THREAD

**Issue by mtrberzi** [CVC4/CVC4#2060]
Flags: `-m --strings-exp`

Error:

```
(error "Unreachable code reached.; static bool CVC4::theory::strings::TheoryStringsRewriter::testConstStringInRegExp(CVC4::String&, nsigned int, CVC4::TNode)
../../../../src/theory/strings/theory_strings_rewriter.cpp:1019
")
```

Instance:
```
(set-logic QF_S)

(declare-const action String)
(declare-const example_key String)

(assert (str.in.re action (re.++
                           (str.to.re "foobar:ab")
                           (re.* re.allchar)
                   )))

(declare-const action_1 String)
(declare-const action_2 String)

(assert (and
         (= action (str.++ action_1 example_key action_2))
         (= action_1 "foobar:a")
         ))

(check-sat)
(get-model)
```

**Comment by mtrberzi** [comment]
In addition, the following very similar instance is solved without the error:
```
(set-logic QF_S)

(declare-const action String)
(declare-const example_key String)

(assert (str.in.re action (re.++
                         ; (str.to.re "foobar:ab")
                           (re.* re.allchar)
                           (str.to.re "foobar:ab")
                   )))

(declare-const action_1 String)
(declare-const action_2 String)

(assert (and
         (= action (str.++ action_1 example_key action_2))
         (= action_1 "foobar:a")
         ))

(check-sat)
(get-model)
```

**Comment by 4tXJ7f** [comment]
I can confirm that CVC4 has an issue on this input. Using a debug build, I am getting the following error message:

```
(error "Internal error detected
bool CVC4::smt::SmtEnginePrivate::simplifyAssertions()
../../../../src/smt/smt_engine.cpp:3876:


A bad expression was produced.  Original exception follows:
Error during type checking: expecting regexp terms in regexp concat
(re.++ ""b"" (re.* REGEXP_SIGMA ))
The ill-typed expression: (re.++ ""b"" (re.* REGEXP_SIGMA ))")
```

I'll investigate.

**Comment by ajreynol** [comment]
Thanks for the bug report, I've fixed this in PR #2066.

**Comment by mtrberzi** [comment]
Great, thanks very much! I will re-test once that PR is merged and let you know if any issues persist.
