### ISSUE TITLE
Unexpected unknown

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#3697]
With the latest cvc4 version on windows
```
This is CVC4 version 1.8-prerelease
compiled with GCC version 5.3.1 20160211
on Jan 30 2020 12:07:03
```
one gets when using the attached file
[cvc4UnexpectedUnknown.min.smt2.txt](https://github.com/CVC4/CVC4/files/4147805/cvc4UnexpectedUnknown.min.smt2.txt)
with `cvc4 --lang=smt2.5 --incremental --strings-exp --fmf-fun-rlv --uf-ss-fair --no-strings-print-ascii .\cvc4UnexpectedUnknown.min.smt2.txt`
``` 
sat 
unknown
```
yet by removing push and pop on line 5 and 7, one gets
``` 
sat 
sat
```
Is this due to a bug? 
I hadn't expect this difference.

**Comment by pjljvandelaar** [comment]
Similar behaviour is observed with
[cvc4Unexpected.min.smt2.txt](https://github.com/CVC4/CVC4/files/4148342/cvc4Unexpected.min.smt2.txt)

Also solved when push & pop 0n line 5 & 7 are outcommented.

**Comment by ajreynol** [comment]
There is nonlinear (integer) arithmetic in this problem: e.g. `(mod 1 vd)` is a term in the above benchmark.  Thus, "unknown" can be expected behavior.

I will look into why commenting out lines 5, 7 causes the change.

**Comment by pjljvandelaar** [comment]
So getting unknown on the last two check-sats in
```
(set-info :smt-lib-version 2.5)
(set-option :produce-models true)
(set-logic ALL)

(assert (= 2 (mod (- 14) 16)))
(check-sat)

(assert (= 2 (mod (- 14) (- 16))))
(check-sat)

(declare-fun v30() Int)
(assert (= 2 (mod (- 14) v30)))
(check-sat)

(declare-fun v31() Int)
(assert (= 2 (mod (- 14) (+ (- 1) v31))))
(check-sat)


(declare-fun v28() Int)
(assert (= 2 (ite (= 0 v28) (- 14) (mod (- 14) (+ (- 1) v28)))))
(check-sat)

(declare-fun v29() Int)
(assert (= 2 (ite (= 0 (+ (- 1) v29)) (- 14) (mod (- 14) (+ (- 1) v29)))))
(check-sat)

(define-funs-rec (
(f0((v4 Int))Int)
)(
(ite (= 0 (+ (- 1) v4)) (- 14) (mod (- 14) (+ (- 1) v4)))
))

(declare-fun v32() Int)
(assert (= 2 (f0 v32)))
(check-sat)
```
is good behaviour, despite that similar problems are solved?

**Comment by ajreynol** [comment]
You can get sat on the second to last one with `--nl-ext-tplanes` (in general, you should use this option whenever you would prefer CVC4 to put more effort instead of answering unknown for non-linear problems)

**Comment by pjljvandelaar** [comment]
--nl-ext-tplanes does seem to help (on windows):
```
PS C:\TorXakis\TorXakis.RefactorAll> cvc4 --version
This is CVC4 version 1.8-prerelease
compiled with GCC version 5.3.1 20160211
on Feb 13 2020 12:13:59
```
```
PS C:\TorXakis\TorXakis.RefactorAll> cvc4 --lang=smt2.5 --incremental --strings-exp --fmf-fun-rlv --uf-ss-fair --no-strings-print-ascii .\sys\txs-smt\logSMT.2020-02-17-09-02-55.5875218.smt2
sat
unknown
```
```
PS C:\TorXakis\TorXakis.RefactorAll> cvc4 --lang=smt2.5 --incremental --strings-exp --fmf-fun-rlv --uf-ss-fair --no-strings-print-ascii --nl-ext-tplanes .\sys\txs-smt\logSMT.2020-02-17-09-02-55.5875218.smt2
sat
unknown
```
with the attached file (changed to txt for upload to github)
[logSMT.2020-02-17-09-02-55.5875218.smt2.txt](https://github.com/CVC4/CVC4/files/4212547/logSMT.2020-02-17-09-02-55.5875218.smt2.txt)

Still removing the push and pop result in `sat`!

**Comment by pjljvandelaar** [comment]
Since preventing this `unknown` is important to me I tried to minimize the problem to help you in diagnosing
The minimal model seems to be:
```
(set-info :smt-lib-version 2.5)
(set-option :produce-models true)
(set-logic ALL)
(define-funs-rec (
(f1d((v12d Int)(v12e Bool))Bool)
(f11()Bool)
(f2((v1f Int))Int)
(f1((v14 Int))Int)
)(
(ite (= 1 (f2 (ite (= 0 v12d) (- 13) (mod (- 13) v12d)))) true v12e) 
(<= 0 (ite (= 0 (f1 0)) 12 (mod 12 (f1 0))))
 v1f 
 v14 
))
(push 1)
(check-sat)
(pop 1)
(push 1)
(assert (f1d (- 13) true))
(check-sat)
(pop 1)
```
With `cvc4 --lang=smt2.5 --incremental --strings-exp --fmf-fun-rlv --uf-ss-fair --no-strings-print-ascii --nl-ext-tplanes`, one gets `sat unknown`.

Removing or simplify any of these statements results in `sat sat`!
Simplifications I have tried are
* removing parameters by using their values, 
* replacing function calls by the value they result in
* removing `f11`, since it is NOT needed for `f1d`

**Comment by ajreynol** [comment]
Thanks for the simplification, I will take a look at this again now.

**Comment by ajreynol** [comment]
As an internal note, this we solve "sat sat" with `--fmf-fun -i` alone.

**Comment by ajreynol** [comment]
@pjljvandelaar , there is an issue with options configurations in CVC4.  For now, you can add `--mbqi=fmc` to your command line, which should solve this.  I will look into making your combinations of options not require this by default.

**Comment by pjljvandelaar** [comment]
@ajreynol Thanks for your suggestions.
Yet I still hope that since all these cases have a div / mod operator with a constant, that with the bug fix of https://github.com/CVC4/CVC4/pull/3766 we will already get sat.
Unfortunately, no nightly build is available yet at https://cvc4.cs.stanford.edu/downloads/builds/win64-opt/unstable/
to test it!

**Comment by pjljvandelaar** [comment]
Just downloaded the latest cvc4 version.
Without the additional flags I still get `unknown`: so the bug #3765 was not causing the `unknown`.
With `cvc4 --lang=smt2.5 --incremental --strings-exp --fmf-fun-rlv --uf-ss-fair --no-strings-print-ascii --nl-ext-tplanes --mbqi=fmc` I get `sat`!

Although it is not want a user might want (a lot of flags have to be added) but the issue could be closed if you want to.

**Comment by ajreynol** [comment]
With regards to the long string of options, you can likely omit `--uf-ss-fair` (it is enabled by default).  I am going to try to make it so that you don't need `--mbqi=fmc` as well. I'll keep this issue open until this is resolved.

**Comment by pjljvandelaar** [comment]
Could you also look into this unexpected unknown:
[logSMT.2020-03-02-16-20-16.5902545.smt2.txt](https://github.com/CVC4/CVC4/files/4276175/logSMT.2020-03-02-16-20-16.5902545.smt2.txt)

```cvc4 --lang=smt2.5 --incremental --fmf-fun-rlv --uf-ss-fair  --strings-exp --no-strings-print-ascii --nl-ext-tplanes --mbqi=fmc logSMT.2020-03-02-16-20-16.5902545.smt2.txt```
yields
```
sat
sat
sat
sat
sat
sat
sat
sat
sat
sat
unknown
```

**Comment by pjljvandelaar** [comment]
@ajreynol Found another strange example today:
` cvc4 --lang=smt2.5 --incremental --fmf-fun-rlv --strings-exp --no-strings-print-ascii --nl-ext-tplanes --mbqi=fmc` on windows with this example yields `unknown` for the last `(check-sat)`.
```
(set-info :smt-lib-version 2.5)
(set-option :produce-models true)
(set-logic ALL)
(define-funs-rec (
(f3a((v6a Int))Int)
(f1((v2 Int))Int)
)(
v6a
(f3a (ite (= 0 v2) 27 (mod 27 v2)))
))
(push 1)
(check-sat)
(pop 1)
(push 1)
(declare-fun v7c() Int)
(assert (= 27 (f1 v7c)))
(assert (= (- 43) v7c))
(check-sat)
(pop 1)
```

Yet, outcommenting line 12, or 11&13 makes the last `(check-sat)` return `sat`

```
> cvc4 --version
This is CVC4 version 1.8-prerelease
compiled with GCC version 5.3.1 20160211
on Mar  1 2020 12:16:02
```

**Comment by ajreynol** [comment]
The last benchmark still has issues with `--strings-exp` causing "unknown"; with only `-i`, we get 2 sat responses.
